### ISSUE TITLE
can't work

### ISSUE THREAD

**Issue by liunaijie** [reggoodwin/ferrit#2]
当我按照文档执行命令时：
![image](https://user-images.githubusercontent.com/28497357/33416650-bac295f0-d5d8-11e7-85ad-fa900ba43a78.png)
会出现如下的情况：
![image](https://user-images.githubusercontent.com/28497357/33416662-c6353cf8-d5d8-11e7-9fe8-3922c5099d03.png)
中间是下载的`http://www.w3.org/`的源码，没有进行截图
![image](https://user-images.githubusercontent.com/28497357/33416950-2d74e0d4-d5da-11e7-803e-c45f25742a14.png)

**Comment by tododo** [comment]
看不清楚截图，能贴一下日志吗？

**Comment by LNJ96** [comment]
当我在命令行执行命令时，`-d`后面的参数无法被识别，当我用postman工具发送请求参数才可以被识别
